# METADATA

In [1]:
import pandas as pd
import json
import gzip
import os

In [2]:

path ="../../archivos/metadata.json.gz"
import json
import gzip
def parse(path):
#Abrir gzip
#Open gzip
    g = gzip.open(path, 'r')
    for l in g:
        yield eval(l)

#Convertir a  json estricto
#Turn to strict json
def parse(path):
    g = gzip.open(path, 'r')
    for l in g:
        yield json.dumps(eval(l))
    f = open("output.strict", 'w')
    for l in parse("archivos\metadata.json.gz"):
        f.write(l + '\n')

#Pandas data frame
import pandas as pd
import gzip
def parse(path):
    g = gzip.open(path, 'rb')
    for l in g:
        yield eval(l)
def getDF(path):
    i = 0
    df = {}
    for d in parse(path):
        df[i] = d
        i += 1
    return pd.DataFrame.from_dict(df, orient='index')

df = getDF('../../archivos/metadata.json.gz')

In [3]:
dfsecure = df.copy()

In [43]:
df2 = dfsecure.copy()

In [ ]:
df.to_csv("../../archivos_csv/metadata_model.csv")

In [ ]:
#Lectura csv

metadata = pd.read_csv("../../archivos_csv/metadata.csv")

In [5]:
metadata

,Unnamed: 0,asin,salesRank,categories,related
0,0,0001048791,{'Books': 6334800},[['Books']],NaN
1,1,0000143561,{'Movies & TV': 376041},"[['Movies & TV', 'Movies']]","{'also_viewed': ['B0036FO6SI', 'B000KL8ODE', '..."
2,2,0000037214,{'Clothing': 1233557},"[['Clothing, Shoes & Jewelry', 'Girls'], ['Clo...","{'also_viewed': ['B00JO8II76', 'B00DGN4R1Q', '..."
3,3,0000032069,NaN,"[['Sports & Outdoors', 'Other Sports', 'Dance'...","{'also_bought': ['0000032050', 'B00D0DJAEG', '..."
4,4,0000031909,{'Toys & Games': 201847},"[['Sports & Outdoors', 'Other Sports', 'Dance']]","{'also_bought': ['B002BZX8Z6', 'B00JHONN1S', '..."
...,...,...,...,...,...
9430083,9430083,B00LZFHL7Y,NaN,"[['Books', 'Literature & Fiction', 'Erotica'],...","{'also_bought': ['B00LXK4KIO', 'B00LZ19FE0', '..."
9430084,9430084,B00LV8M74W,NaN,"[['Books', 'Literature & Fiction', 'Genre Fict...","{'also_bought': ['B00LYOC1R6', 'B00L0WXZIG', '..."
9430085,9430085,B00LXQXLGU,NaN,[['Amazon Instant Video']],NaN
9430086,9430086,B00LV8STE4,NaN,"[['Books', 'Arts & Photography', 'Music', 'Mus...",NaN
9430087,9430087,SMLRBIMX03,{'Musical Instruments': 107527},"[['Musical Instruments', 'Instrument Accessori...","{'also_viewed': ['B003SRHFIW', 'B001E95KJC', '..."

In [96]:
import pandas as pd
from ast import literal_eval
import numpy as np


# check the type of the first value in Pollutants
>>> print(type(df.iloc[0, 1]))
<class 'str'>

# replace NaN with '{}' if the column is strings, otherwise replace with {}
df.Pollutants = df.Pollutants.fillna('{}')  # if the NaN is in a column of strings
# df.Pollutants = df.Pollutants.fillna({i: {} for i in df.index})  # if the column is not strings

# Convert the column of stringified dicts to dicts
# skip this line, if the column contains dicts
df.Pollutants = df.Pollutants.apply(literal_eval)

# reset the index if the index is not unique integers from 0 to n-1
# df.reset_index(inplace=True)  # uncomment if needed

# remove and normalize the column of dictionaries, and join the result to df
df = df.join(pd.json_normalize(df.pop('Pollutants')))

# display(df)
   Station ID    a    b    c
0        8809   46    3   12
1        8810   36    5    8
2        8811  NaN    2    7
3        8812  NaN  NaN   11
4        8813   82  NaN   15
5        8814  NaN  NaN  NaN

In [17]:
#Chequear datatypes de columnas
# Checking dtypes
print(type(dfsecure.iloc[0, 1]))
print(dfsecure.dtypes)

<class 'dict'>

In [ ]:
#Evaluamos el contenido literal de cada registro de related para pasar de string a diccionario
#Eval the literal content of each related row in order to turn it from string to dict
from ast import literal_eval
dfsecure.related = dfsecure.related.apply(literal_eval)

In [19]:
dfsecure.reset_index(inplace=True)

In [22]:
# Expandimos related a multiples columnas segun las keys del diccionario que contiene
# Expand related to multiple columns
df2secure = dfsecure.join(pd.json_normalize(dfsecure.pop('related')))

In [30]:
#Reemplazamos NaN Y nan por N/A
#fillna
df2secure.salesRank = df2secure.salesRank.fillna('N/A')
df2secure.imUrl = df2secure.imUrl.fillna('N/A')
df2secure.categories = df2secure.categories.fillna('N/A')
df2secure.title = df2secure.title.fillna('N/A')
df2secure.description = df2secure.description.fillna('N/A')
df2secure.price = df2secure.price.fillna(0.00)
df2secure.brand = df2secure.brand.fillna('N/A')
df2secure.also_viewed = df2secure.also_viewed.fillna('N/A')
df2secure.buy_after_viewing = df2secure.buy_after_viewing.fillna('N/A')
df2secure.also_bought = df2secure.also_bought.fillna('N/A')
df2secure.bought_together = df2secure.bought_together.fillna('N/A')

In [31]:
df2secure.head(3)

,index,asin,salesRank,imUrl,categories,title,description,price,brand,also_viewed,buy_after_viewing,also_bought,bought_together
0,0,0001048791,{'Books': 6334800},http://ecx.images-amazon.com/images/I/51MKP0T4...,[[Books]],"The Crucible: Performed by Stuart Pankin, Jero...",N/A,0.00,N/A,N/A,N/A,N/A,N/A
1,1,0000143561,{'Movies & TV': 376041},http://g-ecx.images-amazon.com/images/G/01/x-s...,"[[Movies & TV, Movies]]","Everyday Italian (with Giada de Laurentiis), V...","3Pack DVD set - Italian Classics, Parties and ...",12.99,N/A,"[B0036FO6SI, B000KL8ODE, 000014357X, B0037718R...","[B0036FO6SI, B000KL8ODE, 000014357X, B0037718RC]",N/A,N/A
2,2,0000037214,{'Clothing': 1233557},http://ecx.images-amazon.com/images/I/31mCncNu...,"[[Clothing, Shoes & Jewelry, Girls], [Clothing...",Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,N/A,6.99,Big Dreams,"[B00JO8II76, B00DGN4R1Q, B00E1YRI4C]",N/A,N/A,N/A

In [34]:
# Convertimos a str las siguiente columnas para poder aplicarle metodos str
# Turn to string the following columns in order to apply str methods
df2secure.salesRank = df2secure.salesRank.astype(str)
df2secure.categories = df2secure.categories.astype(str)

In [35]:
df2secure.dtypes

index                  int64
asin                  object
salesRank             object
imUrl                 object
categories            object
title                 object
description           object
price                float64
brand                 object
also_viewed           object
buy_after_viewing     object
also_bought           object
bought_together       object
dtype: object

In [37]:
#Reemplazamos los siguientes valores para que no interfieran con la creacion de esquemas automatizada de BigQuery
#Replace the following values so they dont interfere with the automated schema creator from BigQuery
df2secure['categories'] = df2secure['categories'].str.replace('[','')
df2secure['categories'] = df2secure['categories'].str.replace(']','')
df2secure['categories'] = df2secure['categories'].str.replace(']','')
df2secure['categories'] = df2secure['categories'].str.replace("'",'')
df2secure['salesRank'] = df2secure['salesRank'].str.replace("{",'')
df2secure['salesRank'] = df2secure['salesRank'].str.replace("}",'')
df2secure['salesRank'] = df2secure['salesRank'].str.replace("'",'')
df2secure['also_viewed'] = df2secure['also_viewed'].str.replace("[",'')
df2secure['also_viewed'] = df2secure['also_viewed'].str.replace("]",'')
df2secure['buy_after_viewing'] = df2secure['buy_after_viewing'].str.replace("[",'')
df2secure['buy_after_viewing'] = df2secure['buy_after_viewing'].str.replace("]",'')
df2secure['also_bought'] = df2secure['also_bought'].replace('[','')
df2secure['also_bought'] = df2secure['also_bought'].replace(']','')
df2secure['bought_together'] = df2secure['bought_together'].str.replace("[",'')
df2secure['bought_together'] = df2secure['bought_together'].str.replace("]",'')

C:\Users\gomez\AppData\Local\Temp\ipykernel_24372\2792675264.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2secure['categories'] = df2secure['categories'].str.replace('[','')
C:\Users\gomez\AppData\Local\Temp\ipykernel_24372\2792675264.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2secure['categories'] = df2secure['categories'].str.replace(']','')
C:\Users\gomez\AppData\Local\Temp\ipykernel_24372\2792675264.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2secure['categories'] = df2secure['categories'].str.replace(']','')
C:\Users\gomez\AppData\Local\Temp\ipykernel_24372\2792675264.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2secure['salesRank'] = df2secure['salesRank'].str.replace("{",'')
C:\Users\gomez\AppData\Local\Temp\ipykernel_24372\2792675264.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2secure['salesRank'] = df2secure['salesRank'].str.replace("}",'')

In [38]:
df2secure

,index,asin,salesRank,imUrl,categories,title,description,price,brand,also_viewed,buy_after_viewing,also_bought,bought_together
0,0,0001048791,Books: 6334800,http://ecx.images-amazon.com/images/I/51MKP0T4...,Books,"The Crucible: Performed by Stuart Pankin, Jero...",N/A,0.00,N/A,N/A,N/A,N/A,N/A
1,1,0000143561,Movies & TV: 376041,http://g-ecx.images-amazon.com/images/G/01/x-s...,"Movies & TV, Movies","Everyday Italian (with Giada de Laurentiis), V...","3Pack DVD set - Italian Classics, Parties and ...",12.99,N/A,"[B0036FO6SI, B000KL8ODE, 000014357X, B0037718R...","[B0036FO6SI, B000KL8ODE, 000014357X, B0037718RC]",N/A,N/A
2,2,0000037214,Clothing: 1233557,http://ecx.images-amazon.com/images/I/31mCncNu...,"Clothing, Shoes & Jewelry, Girls, Clothing, Sh...",Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,N/A,6.99,Big Dreams,"[B00JO8II76, B00DGN4R1Q, B00E1YRI4C]",N/A,N/A,N/A
3,3,0000032069,N/A,http://ecx.images-amazon.com/images/I/51EzU6qu...,"Sports & Outdoors, Other Sports, Dance, Clothi...",Adult Ballet Tutu Cheetah Pink,N/A,7.89,BubuBibi,"[B00D0F450I, 0000032050, B00D2JTMS2, 000003204...",N/A,"[0000032050, B00D0DJAEG, 0000032042, B00D0F450...","[0000032050, B00D0DJAEG, 0000032042, B00D0F450I]"
4,4,0000031909,Toys & Games: 201847,http://ecx.images-amazon.com/images/I/41xBoP0F...,"Sports & Outdoors, Other Sports, Dance",Girls Ballet Tutu Neon Pink,High quality 3 layer ballet tutu. 12 inches in...,7.00,Unknown,"[B002BZX8Z6, B00JHONN1S, B008F0SU0Y, B00E1YRI4...",N/A,"[B002BZX8Z6, B00JHONN1S, 0000031895, B00D2K1M3...",[B002BZX8Z6]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9430083,9430083,B00LZFHL7Y,N/A,http://ecx.images-amazon.com/images/I/41RDitlH...,"Books, Literature & Fiction, Erotica, Kindle S...",N/A,N/A,0.99,N/A,N/A,"[B00LDD8NDO, B00KLBHX44, B00JS9YJPQ, B00LADEH0U]","[B00LXK4KIO, B00LZ19FE0, B00LZ4D0UC, B00LNQ27T...",N/A
9430084,9430084,B00LV8M74W,N/A,http://ecx.images-amazon.com/images/I/51qUjk4b...,"Books, Literature & Fiction, Genre Fiction, Me...",N/A,N/A,3.99,N/A,N/A,[B004Q3RTXS],"[B00LYOC1R6, B00L0WXZIG, B00JCZSTDE, B00JWGG0Q...",N/A
9430085,9430085,B00LXQXLGU,N/A,N/A,Amazon Instant Video,N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A
9430086,9430086,B00LV8STE4,N/A,http://ecx.images-amazon.com/images/I/51l7MLl%...,"Books, Arts & Photography, Music, Musical Genr...",N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A
9430087,9430087,SMLRBIMX03,Musical Instruments: 107527,http://ecx.images-amazon.com/images/I/31R3EGJN...,"Musical Instruments, Instrument Accessories, G...","LR Baggs iMix w/IBeam, Element, Preamp, Mixer,...",The iMix from LR Baggs combines the IBeam and ...,229.00,LR Baggs,"[B003SRHFIW, B001E95KJC, B003VXNPN2, B001E95KG...","[B003SRHFIW, B003VXNPN2, B001E95KJC]",N/A,N/A

In [40]:
#Copia de seguridad
df2secure.to_csv('../../archivos_csv/metadatafinale.csv')

In [41]:
#Convertimos df a diccionario para iterarlo
#Turn df to dict and iter
df_dict = df2secure.to_dict('records')
# Iteramos el diccionario para separar la columna salesRank a dos segun clave y contenido del diccionario
# Los diferentes try, except evitan inconvenientes con las anomalias del df

#Iter the dict to expand salesRank column
for i, x in enumerate(df_dict):
    try:
        try:
            rank = int(x["salesRank"])
            category = "N/A"
        except:
            if x["salesRank"] == "N/A" or x["salesRank"] == {} or x['salesRank'] == '':
                category = "N/A"
                rank = "N/A"
            else:
                data = x["salesRank"].split(": ")
                category = data[0]
                rank = data[1]
        x["category"] = category
        x["salesRank"] = rank
    except Exception as e:
        print(f"Failed at register nÂº{i}.")
        print(e)

df_final = pd.DataFrame.from_dict(df_dict)
print(df_final)

           index        asin salesRank  \
0              0  0001048791   6334800
1              1  0000143561    376041
2              2  0000037214   1233557
3              3  0000032069       N/A
4              4  0000031909    201847
...          ...         ...       ...
9430083  9430083  B00LZFHL7Y       N/A
9430084  9430084  B00LV8M74W       N/A
9430085  9430085  B00LXQXLGU       N/A
9430086  9430086  B00LV8STE4       N/A
9430087  9430087  SMLRBIMX03    107527

                                                     imUrl  \
0        http://ecx.images-amazon.com/images/I/51MKP0T4...
1        http://g-ecx.images-amazon.com/images/G/01/x-s...
2        http://ecx.images-amazon.com/images/I/31mCncNu...
3        http://ecx.images-amazon.com/images/I/51EzU6qu...
4        http://ecx.images-amazon.com/images/I/41xBoP0F...
...                                                    ...
9430083  http://ecx.images-amazon.com/images/I/41RDitlH...
9430084  http://ecx.images-amazon.com/images/I/51qUjk4b...
9430085                                                N/A
9430086  http://ecx.images-amazon.com/images/I/51l7MLl%...
9430087  http://ecx.images-amazon.com/images/I/31R3EGJN...

                                                categories  \
0                                                    Books
1                                      Movies & TV, Movies
2        Clothing, Shoes & Jewelry, Girls, Clothing, Sh...
3        Sports & Outdoors, Other Sports, Dance, Clothi...
4                   Sports & Outdoors, Other Sports, Dance
...                                                    ...
9430083  Books, Literature & Fiction, Erotica, Kindle S...
9430084  Books, Literature & Fiction, Genre Fiction, Me...
9430085                               Amazon Instant Video
9430086  Books, Arts & Photography, Music, Musical Genr...
9430087  Musical Instruments, Instrument Accessories, G...

                                                     title  \
0        The Crucible: Performed by Stuart Pankin, Jero...
1        Everyday Italian (with Giada de Laurentiis), V...
2        Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...
3                           Adult Ballet Tutu Cheetah Pink
4                              Girls Ballet Tutu Neon Pink
...                                                    ...
9430083                                                N/A
9430084                                                N/A
9430085                                                N/A
9430086                                                N/A
9430087  LR Baggs iMix w/IBeam, Element, Preamp, Mixer,...

                                               description   price  \
0                                                      N/A    0.00
1        3Pack DVD set - Italian Classics, Parties and ...   12.99
2                                                      N/A    6.99
3                                                      N/A    7.89
4        High quality 3 layer ballet tutu. 12 inches in...    7.00
...                                                    ...     ...
9430083                                                N/A    0.99
9430084                                                N/A    3.99
9430085                                                N/A    0.00
9430086                                                N/A    0.00
9430087  The iMix from LR Baggs combines the IBeam and ...  229.00

              brand                                        also_viewed  \
0               N/A                                                N/A
1               N/A  [B0036FO6SI, B000KL8ODE, 000014357X, B0037718R...
2        Big Dreams               [B00JO8II76, B00DGN4R1Q, B00E1YRI4C]
3          BubuBibi  [B00D0F450I, 0000032050, B00D2JTMS2, 000003204...
4           Unknown  [B002BZX8Z6, B00JHONN1S, B008F0SU0Y, B00E1YRI4...
...             ...                                                ...
9430083         N/A                                                N/A
9430084         N/A                                                N/A
9430085         N/A                                                N/A
9430086         N/A                                                N/A
9430087    LR Baggs  [B003SRHFIW, B001E95KJC, B003VXNPN2, B001E95KG...

                                        buy_after_viewing  \
0                                                     N/A
1        [B0036FO6SI, B000KL8ODE, 000014357X, B0037718RC]
2                                                     N/A
3                                                     N/A
4                                                     N/A
...                                                   ...
9430083  [B00LDD8NDO, B00KLBHX44, B00JS9YJPQ, B00LADEH0U]
9430084                                      [B004Q3RTXS]
9430085                                               N/A
9430086                                               N/A
9430087              [B003SRHFIW, B003VXNPN2, B001E95KJC]

                                               also_bought  \
0                                                      N/A
1                                                      N/A
2                                                      N/A
3        [0000032050, B00D0DJAEG, 0000032042, B00D0F450...
4        [B002BZX8Z6, B00JHONN1S, 0000031895, B00D2K1M3...
...                                                    ...
9430083  [B00LXK4KIO, B00LZ19FE0, B00LZ4D0UC, B00LNQ27T...
9430084  [B00LYOC1R6, B00L0WXZIG, B00JCZSTDE, B00JWGG0Q...
9430085                                                N/A
9430086                                                N/A
9430087                                                N/A

                                          bought_together             category
0                                                     N/A                Books
1                                                     N/A          Movies & TV
2                                                     N/A             Clothing
3        [0000032050, B00D0DJAEG, 0000032042, B00D0F450I]                  N/A
4                                            [B002BZX8Z6]         Toys & Games
...                                                   ...                  ...
9430083                                               N/A                  N/A
9430084                                               N/A                  N/A
9430085                                               N/A                  N/A
9430086                                               N/A                  N/A
9430087                                               N/A  Musical Instruments

[9430088 rows x 14 columns]

In [43]:
#Almaceno en local
df_final.to_csv('../../archivos_csv/metaGOD.csv')

In [ ]:
#Importo lo necesario para cargar a gbq
#gbq dependencies
from pandas.io import gbq
from google.cloud import bigquery
import os

credentials_path = 'D:/Henry/DATA-PF/PF-DATASCIENCE/Modelo/credentials.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credentials_path

In [ ]:
#Creamos chunks definiendo en size la cantidad de registros por chunk
#Create chunks to export
size = 1000000
list_of_dfs = [df_final.loc[i: i + size - 1,: ] for i in range(0, len(df_final), size)]

In [ ]:
#Ejecutamos la carga a gbq 
#Export to gbq
for x in list_of_dfs:
    x.to_gbq(destination_table='SR.metaLORD',project_id='pf-henry-365404',if_exists='append')